spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=project_blog
    username: sa
    password: 123
  data:
    cassandra:
      schema-action: create_if_not_exists
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: org.hibernate.dialect.SQLServer2012Dialect